Test `QMenu.addAction` with various shortcut types
Test `QMenu.addAction` with a shortcut of `Qt.Key` type as well. The argument type causes the following error on `PySide2`:
```plaintext
TypeError: 'PySide2.QtWidgets.QAction.setShortcut' called with wrong argument types:
  PySide2.QtWidgets.QAction.setShortcut(Key)
Supported signatures:
  PySide2.QtWidgets.QAction.setShortcut(PySide2.QtGui.QKeySequence)
```